services:
  database:
    image: 'docker.io/library/postgres:17@sha256:6efd0df010dc3cb40d5e33e3ef84acecc5e73161bd3df06029ee8698e5e12c60'
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=passwordmanager
      - POSTGRES_PASSWORD=passwordmanager
      - POSTGRES_DB=passwordmanager
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: { }